version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - teather-scrapper-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  teather-scrapper-db:
